## Analiza exploratorie a datelor cu Pandas

**În această sarcină trebuie să folosești Pandas pentru a răspunde la câteva întrebări despre datasetul [Adult](https://archive.ics.uci.edu/ml/datasets/Adult). (Nu trebuie să descărcați datele - sunt deja aici). **

Valori unice ale tuturor caracteristicilor (pentru mai multe informații, consultați linkul de mai sus):
- `age`: continuous.
- `workclass`: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- `fnlwgt`: continuous.
- `education`: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- `education-num`: continuous.
- `marital-status`: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- `occupation`: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- `relationship`: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- `race`: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- `sex`: Female, Male.
- `capital-gain`: continuous.
- `capital-loss`: continuous.
- `hours-per-week`: continuous.
- `native-country`: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- `salary`: >50K,<=50K

In [ ]:
import pandas as pd

In [ ]:
!mkdir data && curl -o data/adult.data.csv -LJO https://github.com/dianaartiom/machine_learning_with_python/raw/main/lesson03/notebooks/data/adult.data.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    389      0 --:--:-- --:--:-- --:--:--   389
100 3436k  100 3436k    0     0  3990k      0 --:--:-- --:--:-- --:--:-- 3990k

In [ ]:
data = pd.read_csv('data/adult.data.csv')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Câți bărbați și câte femei (caracteristica *sex*) sunt reprezentați în acest set de date?**

In [ ]:
# Scrie solutia ta aici

**2. Care este vârsta medie (caracteristica *age*) a femeilor?**

In [ ]:
# Scrie solutia ta aici

**3. Care este procentul de cetățeni germani (caracteristica *native-country*)?**

In [ ]:
# Scrie solutia ta aici

**4-5. Care sunt media și abaterea standard (standard deviation) a vârstei pentru cei care câștigă mai mult de 50 000 de euro pe an (caracteristica *salary*) și pentru cei care câștigă mai puțin de 50 000 de euro pe an?**

In [ ]:
# Scrie solutia ta aici

**6. Este adevărat că toate persoanele care câștigă mai mult de 50.000 de dolari au studii universitare? (*education -  Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* sau *Doctorate*)**

In [ ]:
# Scrie solutia ta aici

**7. Afișați statisticile privind vârsta pentru fiecare rasă (caracteristica *race*) și pentru fiecare sex (caracteristica *sex*). Utilizați *groupby()* și *describe()*. Găsiți vârsta maximă a bărbaților de rasă *Amer-Indian-Eskimo*.**

In [ ]:
# Scrie solutia ta aici

**8. În rândul cui este mai mare proporția celor care câștigă mult (>50.000): bărbați căsătoriți sau necăsătoriți (caracteristica *marital-status*)? Considerați ca fiind căsătoriți pe cei care au un *marital-status* care începe cu *Married* (Married-civ-spouse, Married-spouse-absent sau Married-AF-spouse), restul sunt considerați necasatoriti.**

In [ ]:
# Scrie solutia ta aici

**9. Care este numărul maxim de ore pe săptămână pe care o persoană le lucrează (caracteristica *hours-per-week*)? Câte persoane lucrează un astfel de număr de ore și care este procentul celor care câștigă mult (>50K) dintre acestea?**

In [ ]:
# Scrie solutia ta aici

**10. Calculați timpul mediu de lucru (*hours-per-week*) pentru cei care câștigă puțin (<=50K) și mult (>50K) (*salariu*) pentru fiecare țară (*native-country*). Care vor fi acestea pentru Japonia?**

In [ ]:
# Scrie solutia ta aici

## Vizualizarea datelor
**Afiseaza diagrama de histograme pentru caracteristica *fnlwgt* cu ajutorul metodei .hist() a dataframe-ului. Exploreaza diferite grafice pasand functiei .hist() parametrul bins (e.g. chemam .hist(bins=6))**

In [ ]:
# Scrie solutia ta aici

**Afiseaza diagrama de densitate pentru caracteristica *capital-gain* cu ajutorul metodei .plot() a dataframe-ului.**

In [ ]:
# Scrie solutia ta aici

**Afiseaza diagrama box-plot pentru caracteristica *hours-per-week* cu ajutorul librariei seaborn (importata cu denumirea sns).**

In [ ]:
# Scrie solutia ta aici

**Ce putem conclude despre caracteristica *hours-per-week*?**
Dublu click pe aceasta celula si scrie textul tau aici.

**Afiseaza diagrama de bare (bar plot) pentru caracteristicile *salary*, *marital-status* si *relationship*. Foloseste libraria matplotlib (importata cu numele plt). **

In [ ]:
# Scrie solutia ta aici

**Afiseaza matricea de corelatie intre caracteristicile numerice. Calculeaza matricea de colelatie cu ajutorul functiei *corr()* a dataframe-ului si afiseaza graficul cu ajutorul functiei *heatmap()* a librariei sns.**

In [ ]:
# Scrie solutia ta aici